### ISSUE TITLE
Add SQL Support For C# Statements

### ISSUE THREAD

**Issue by andrejohansson** [conwid/AzureDocumentDbDriver#2]
Hello, thanks for your work on this!

Would it be possible to add support of executing sql queries against a collection from c#?

Something like:
```csharp
MyCollection.Query("SELECT x FROM x WHERE...").Take(10).Dump();
```

```csharp
MyCollection.Query("SELECT x FROM x WHERE...").Cast<MyType>().Single(i => i.Prop == "something");
```
This would give us the ability to initiate queries with sql to do the heavy lifting and then narrow down the results and transition to c#/linq.

I know about the support for SQL today but I cant really use the results there in further code fiddling. :-)

**Comment by conwid** [comment]
Sure, thanks for the suggestion.
I'll leave it here for a while so if someone wants to join, we can spec the feature and implement it.

I would think that the method `Query` in your description should be named ExecuteSql. I envision a generic version (so no need to specify an extra cast) and a non-generic version that relies heavily on dynamics.

The query itself is executed of course on the server side, and then everything else is basically Linq to Objects queries on the result.

**Comment by conwid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DocumentDb driver](https://trello.com/c/45uDd0DV/1-documentdb-driver)

**Comment by conwid** [comment]
I'm happy to report that I have made progress with this request. You can already check out the source code in the repo (and even download the driver's current version if you look really closely), but I still need some time to hammer out some details.

I suggest to check this repository, my Github account and my blog (dotnetfalcon.com) during the upcoming week as I'm planning on releasing everything then.

**Comment by andrejohansson** [comment]
Nice! But I think your links to the binaries (both from the blog and in the readme) are broken?

**Comment by conwid** [comment]
Thanks for spotting this. Actually, the links were OK, the problem was that I forgot to set the access policy on the blob. Fixed :)
