### ISSUE TITLE
Multiple connections in a single query

### ISSUE THREAD

**Issue by DarinMacRae** [conwid/AzureDocumentDbDriver#3]
Hi, first thanks for the work on this driver. It's good stuff.

I DL'd and installed your driver today because I wanted to use it for migrating documents from one collection to another but in this case they are in different CosmosDB accounts. After some trial and error and looking to see how the [SQL Server folks do it](https://stackoverflow.com/questions/1495357/linqpad-using-multiple-datacontexts) I gave up. No biggie, I can use the .NET libraries directly but thought I'd mention it as a potential use case of interest.

BTW, it's ok if the solution is to just create contexts manually but after spelunking your code it wasn't obvious how to accomplish that.

**Comment by conwid** [comment]
Thanks for bringing my attention to this issue. I think that the current limitations of the extensions API don't allow for this natively, so you'll have to go with the manual solution.

To do this, first download the Static driver context backend class library (link in the readme), then read my blog post here: http://dotnetfalcon.com/linqpad-cosmosdb-data-context-driver-update-part-1/ on how to use it and create contexts manually.

If you still have questions, feel free to ask. I will also update the project wiki with the relevant information.

**Comment by conwid** [comment]
Expanded the wiki to include a tutorial on how to create a context manually:
https://github.com/conwid/AzureDocumentDbDriver/wiki/06.-Creating-contexts-manually

Since the extension API currently does not support cross-connection queries, I'm closing it as "unsupported", but I'll keep watch of new features coming to the extension API (which is not very often, unfortunately).

**Comment by DarinMacRae** [comment]
I had to take another approach but if I return to this driver again I will look at your suggestion. Thanks for taking a look at it.

**Comment by conwid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DocumentDb driver create contexts manually](https://trello.com/c/H1OlHp5D/3-documentdb-driver-create-contexts-manually)
