### ISSUE TITLE
Feature request: SSL support 

### ISSUE THREAD

**Issue by EM1L** [conwid/AzureDocumentDbDriver#4]
It would be nice if it supports SSL with certificate based authentication.

Definitely something useful for the road map and future enhancements.

Thanks!

**Comment by conwid** [comment]
Thanks for the suggestion. I know it's been a while, but I have been swamped lately.
Can you maybe specify this feature more? What do you exactly mean by SSL with certificate based authentication?

**Comment by conwid** [comment]
As I have received no further information, I'm closing this issue.
