### ISSUE TITLE
Cannot set the partition key for queries/stored procedures [feature request]

### ISSUE THREAD

**Issue by jefflafay** [conwid/AzureDocumentDbDriver#5]
We use partition keys to partition tenants in some of our cosmos databases. I would like to be able to set the feed option property to allow this to happen, otherwise some queries take minutes to come back without the partition key when they should come back in milliseconds.

Not sure how it would work for stored procedures but I also need it for that as well. I tried running a stored procedure today and I received an exception stating that I was missing the partition key.

Thanks!

**Comment by conwid** [comment]
Added support for this in 2.2.0.0. Check out the wiki for more info.
